name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next
        run: npm run build:next

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Build Electron
        run: npm run build
        env:
          CI: true
